#Install a Terraform executable locally
before_install:
  - cd ./example
  - wget https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
  - unzip terraform_0.12.20_linux_amd64.zip

#These two steps will effectively validate our terraform and output a list of any changes to be made to our infrastructure
script:
  - ./terraform init
  - ./terraform plan
